name: Re-Usable Workflow

on:
  workflow_call:
    inputs:
      custom_script:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2

      - name: Echo Hello
        run: echo "Hello Workld"

      - name: Custom script
        if: "${{ github.event.inputs.custom_script != '' }}"
        run: ${{inputs.custom_script}}
